import type { jsPDF } from "jspdf";

let cachedLogoPng: string | null = null;

function loadLogoPng(): Promise<string> {
  if (cachedLogoPng) return Promise.resolve(cachedLogoPng);

  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      // Match SVG viewBox for crisp rendering
      canvas.width = 400;
      canvas.height = 120;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        reject(new Error("Canvas not supported"));
        return;
      }
      ctx.drawImage(img, 0, 0, 400, 120);
      cachedLogoPng = canvas.toDataURL("image/png");
      resolve(cachedLogoPng);
    };
    img.onerror = () => reject(new Error("Failed to load logo"));
    img.src = "/logixweave-logo.svg";
  });
}

/**
 * Adds LogixWeave logo (top-right) and website link (bottom-center)
 * to every page of a jsPDF document. Call before doc.save().
 */
export async function addPdfBranding(doc: jsPDF): Promise<void> {
  let logoPng: string | null = null;
  try {
    logoPng = await loadLogoPng();
  } catch {
    // Fall back to text-only branding if logo fails to load
  }

  const totalPages = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const siteHost =
    typeof window !== "undefined" ? window.location.host : "logixweave.com";
  const siteUrl =
    typeof window !== "undefined" ? window.location.origin : "https://logixweave.com";

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Logo in top-right corner (40 x 12 preserves the 400:120 aspect ratio)
    if (logoPng) {
      const logoWidth = 40;
      const logoHeight = 12;
      doc.addImage(
        logoPng,
        "PNG",
        pageWidth - 20 - logoWidth,
        6,
        logoWidth,
        logoHeight
      );
    }

    // Footer centered at bottom of page
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150, 150, 150);
    const prefix = "This document was generated by LogixWeave. Visit us at ";
    const linkY = pageHeight - 10;
    const fullText = prefix + siteHost;
    const fullWidth = doc.getTextWidth(fullText);
    const startX = (pageWidth - fullWidth) / 2;
    doc.text(prefix, startX, linkY);
    const prefixWidth = doc.getTextWidth(prefix);
    // Draw the link portion in a slightly darker shade
    doc.setTextColor(120, 120, 120);
    doc.text(siteHost, startX + prefixWidth, linkY);
    const linkWidth = doc.getTextWidth(siteHost);
    doc.link(startX + prefixWidth, linkY - 3, linkWidth, 4, { url: siteUrl });
    doc.setTextColor(0, 0, 0);
  }
}
