import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

interface TagForExport {
  name: string;
  dataType: string;
  scope: string;
  description?: string;
  value?: string;
  usage?: string;
  radix?: string;
  externalAccess?: string;
  dimensions?: string;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function generateL5XTagFragment(tags: TagForExport[]): string {
  const controllerTags = tags.filter((t) => t.scope === "Controller");
  const programTags = tags.filter((t) => t.scope !== "Controller");

  // Group program tags by scope
  const programGroups = new Map<string, TagForExport[]>();
  for (const tag of programTags) {
    const existing = programGroups.get(tag.scope) || [];
    existing.push(tag);
    programGroups.set(tag.scope, existing);
  }

  let xml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  L5X Tag Import Fragment
  Generated by LogixWeave

  To use this file:
  1. Open Studio 5000
  2. Right-click on Controller Tags or the target Program
  3. Select "Import Tags..."
  4. Select this file
-->
<RSLogix5000Content SchemaRevision="1.0" SoftwareRevision="33.00" ContainsContext="false" ExportDate="...">
`;

  // Controller Tags
  if (controllerTags.length > 0) {
    xml += `  <Controller Use="Context">
    <Tags>
`;
    for (const tag of controllerTags) {
      xml += generateTagXml(tag, 6);
    }
    xml += `    </Tags>
  </Controller>
`;
  }

  // Program Tags (as separate sections for reference)
  for (const [programName, tags] of programGroups) {
    xml += `  <!-- Program: ${escapeXml(programName)} -->
  <Program Name="${escapeXml(programName)}" Use="Context">
    <Tags>
`;
    for (const tag of tags) {
      xml += generateTagXml(tag, 6);
    }
    xml += `    </Tags>
  </Program>
`;
  }

  xml += `</RSLogix5000Content>
`;

  return xml;
}

function generateTagXml(tag: TagForExport, indent: number): string {
  const spaces = " ".repeat(indent);
  let xml = `${spaces}<Tag Name="${escapeXml(tag.name)}" TagType="Base" DataType="${escapeXml(tag.dataType)}"`;

  if (tag.radix) {
    xml += ` Radix="${escapeXml(tag.radix)}"`;
  }

  if (tag.usage) {
    xml += ` Usage="${escapeXml(tag.usage)}"`;
  }

  if (tag.externalAccess) {
    xml += ` ExternalAccess="${escapeXml(tag.externalAccess)}"`;
  }

  if (tag.dimensions) {
    xml += ` Dimensions="${escapeXml(tag.dimensions)}"`;
  }

  if (tag.description || tag.value) {
    xml += `>\n`;
    if (tag.description) {
      xml += `${spaces}  <Description><![CDATA[${tag.description}]]></Description>\n`;
    }
    if (tag.value) {
      xml += `${spaces}  <Data Format="Decorated">\n`;
      xml += `${spaces}    <DataValue DataType="${escapeXml(tag.dataType)}" Value="${escapeXml(tag.value)}"/>\n`;
      xml += `${spaces}  </Data>\n`;
    }
    xml += `${spaces}</Tag>\n`;
  } else {
    xml += `/>\n`;
  }

  return xml;
}

export async function POST(request: Request) {
  try {
    const supabase = await createClient();

    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { tags, projectName } = await request.json();

    if (!tags || !Array.isArray(tags) || tags.length === 0) {
      return NextResponse.json({ error: "tags array is required" }, { status: 400 });
    }

    const l5xContent = generateL5XTagFragment(tags);
    const date = new Date().toISOString().split("T")[0];
    const filename = `${(projectName || "Tags").replace(/[^a-zA-Z0-9]/g, "_")}_Import_${date}.L5X`;

    return new NextResponse(l5xContent, {
      headers: {
        "Content-Type": "application/xml",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("L5X export error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}
